MiintoTasks/MiintoTasks/Models/BrandModel.cs
using MiintoTasks.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiintoTasks.Models
{
    public class BrandModel
    {
        public string Code { get; set; }

        public string Name { get; set; }

        public static IEnumerable<BrandModel> GetBrands(IRepository repository)
        {
            return repository.GetBrands().Select(b => new BrandModel()
            {
                Code = b.Code,
                Name = b.Name
            });
        }

    }
}

MiintoTasks/MiintoTasks/Models/CategoryModel.cs
using MiintoTasks.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiintoTasks.Models
{
    public class CategoryModel
    {
        public string Name { get; set; }

        public static IEnumerable<CategoryModel> GetCategory(IRepository repository)
        {
            return repository.GetCategory().Select(b => new CategoryModel()
            {
                Name = b.Name
            });
        }
    }
}

MiintoTasks/MiintoTasks/Models/ProductModel.cs
using MiintoTasks.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiintoTasks.Models
{
    public class ProductModel
    {
        public string Brand { get; set; }

        public string BrandCode { get; set; }

        public int Stock { get; set; }

        public string ProductTitle { get; set; }

        public string Category { get; set; }

        public string ThumbnailPath {get; set;}


        public static IEnumerable<ProductModel> GetProducts(IEnumerable<ProductDto> products)
        {
            return products.Select(b => new ProductModel()
            {
                Brand = b.Brand,
                BrandCode = b.BrandCode,
                Stock = b.Stock,
                ProductTitle = b.ProductTitle,
                Category = b.Category,
                ThumbnailPath = b.ThumbnailPath
            });
        }
    }
}

MiintoTasks/MiintoTasks/Models/ShowProductsModel.cs
using MiintoTasks.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MiintoTasks.Models
{
    public class ShowProductsModel
    {
        public string SelectedBrand { get; set; }

        public string SelectedCategory { get; set; }


        public IEnumerable<BrandModel> AllBrands { get; set; }

        public IEnumerable<CategoryModel> AllCategory { get; set; }

        public static ShowProductsModel GetShowProductsModel(IRepository repository)
        {
            var result = new ShowProductsModel();

            var brands = new List<BrandModel>()
            {
                new BrandModel()
            };
            brands.AddRange(BrandModel.GetBrands(repository));            
            result.AllBrands = brands;

            var categories = new List<CategoryModel>()
            {
                new CategoryModel()
            };
            categories.AddRange(CategoryModel.GetCategory(repository));
            result.AllCategory = categories;

            return result;
        }

    }
}

MiintoTasks/MiintoTasks/Controllers/CssTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiintoTasks.Controllers
{
    public class CssTaskController : Controller
    {
        // GET: CssTask
        public ActionResult Index()
        {
            return View();
        }
    }
}

MiintoTasks/MiintoTasks/Controllers/NetTaskApiController.cs
using MiintoTasks.Data;
using MiintoTasks.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MiintoTasks.Controllers
{
    public class NetTaskApiController : ApiController
    {
        private readonly IRepository m_repository;

        public NetTaskApiController(IRepository repository)
        {
            m_repository = repository;
        }

        public IEnumerable<ProductModel> GetProducts(string brand = null, string category = null)
        {
            return ProductModel.GetProducts(m_repository.GetProducts(new ProductQueryDto()
            {
                BrandCode = brand,
                Category = category
            }));
        }
    }
}

MiintoTasks/MiintoTasks/Controllers/NetTaskController.cs
using MiintoTasks.Data;
using MiintoTasks.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiintoTasks.Controllers
{
    public class NetTaskController : Controller
    {
        private readonly IRepository m_repository;

        public NetTaskController(IRepository repository)
        {
            m_repository = repository;
        }

        // GET: NetTask
        public ActionResult Index()
        {
            ShowProductsModel model = ShowProductsModel.GetShowProductsModel(m_repository);
            return View(model);
        }
    }
}

MiintoTasks/MiintoTasks/Views/CssTask/Index.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Miinto Premium</title>
    <link href="/Content/CssTask.css" rel="stylesheet">
</head>
<body>
    <div class="title_box">
         <span class="title_box_title">Miinto premium</span>
    </div>
    <div class="full-row">
        <div class="image-col">
            <img alt="women" src="~/Content/img/Image_1.jpg" />
            <div class="img_container">
                <ul>
                    <li><a href="#">Brands</a></li>
                    <li><a href="#">Dresses</a></li>
                    <li><a href="#">Outerwear</a></li>
                    <li><a href="#">Bags</a></li>
                    <li><a href="#">Shoes</a></li>
                </ul>
            </div>
        </div>

        <div class="image-col">
            <img class="img_shadow" alt="men" src="~/Content/img/Image_2.jpg" />
            <div class="img_container">
                <ul>
                    <li><a href="#">Brands</a></li>
                    <li><a href="#">Suits & Blazers</a></li>
                    <li><a href="#">Outwear</a></li>
                    <li><a href="#">Bags</a></li>
                    <li><a href="#">Shoes</a></li>
                </ul>
            </div>
        </div>

        <div class="image-col">
            <img class="img_shadow" alt="kids" src="~/Content/img/Image_3.jpg" />
            <div class="img_container">
                <ul>
                    <li><a href="#">Brands</a></li>
                    <li><a href="#">Outwear</a></li>
                    <li><a href="#">Tops</a></li>
                    <li><a href="#">Bottoms</a></li>
                    <li><a href="#">Shoes</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="full-row">
        <div class="content_title_box">
            <span class="content_title_box_title">Miinto premium</span>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur magna ipsum, placerat non nibh at, fringilla condimentum magna. Morbi sodales fermentum venenatis. Curabitur vitae hendrerit metus. Pellentesque sagittis justo magna, vestibulum convallis urna interdum eget. Nam eu tellus euismod, malesuada urna sit amet, dictum augue. Sed mattis dolor ac dui pellentesque consequat. Nulla facilisi.</p>
            <p>Aenean pharetra eget ex vel egestas. Nulla sollicitudin porta neque id dictum. Morbi dictum auctor ante, sit amet tempus dui blandit at. Suspendisse mattis dui sit amet nulla aliquet, ac ultrices sem sollicitudin. Aliquam dictum egestas velit at rhoncus. Sed felis sem, luctus eu ex non, luctus lacinia odio. Proin orci arcu, eleifend id enim eget, fermentum ultrices nisl. Donec interdum sem justo, quis fermentum enim consequat vitae. Nulla eu lacinia ligula. Vivamus dignissim vel felis ac efficitur. Nulla nec tempus diam. Vivamus id metus dolor. Aliquam viverra nisl placerat neque molestie tempus. Mauris sed quam pretium, lacinia sapien ut, porttitor lacus.</p>
        </div>
    </div>
    
</body>
</html>

MiintoTasks/MiintoTasks/Views/NetTask/Index.cshtml
@{
    ViewBag.Title = "Shop products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model  MiintoTasks.Models.ShowProductsModel


@section Scripts {
    @Scripts.Render("~/Scripts/NetTask/Gallery.js")
}

<h1>@ViewBag.Title</h1>

<div id="galleryContainer">
    <div class="row filter-panel">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.SelectedBrand, "Brand")
                @Html.DropDownListFor(m => m.SelectedBrand, new SelectList(Model.AllBrands, "Code", "Name"), new { data_bind = "value: brand", @class= "form-control notRadious" })
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.SelectedCategory, "Category")
                @Html.DropDownListFor(m => m.SelectedCategory, new SelectList(Model.AllCategory, "Name", "Name"), new { data_bind = "value: category", @class= "form-control notRadious" })
            </div>
        </div>

        <div class="col-md-3 float-right">
            <div class="form-group">
                <label>Search</label>
                <div class="input-group">
                    <span class="input-group-btn notRadious">
                        <button class="btn btn-default notRadious" type="button"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                    <input type="text" class="form-control notRadious">
                </div>
            </div>
        </div>

    </div>
    <div class="row gallery-row" data-bind="foreach: products">
        <div class="gallery-item">
            <img data-bind="attr: { src: ThumbnailPath }" />
            <div class="description">
                <span data-bind="text: ProductTitle"></span>
                <span><br/> by <br/></span>
                <span data-bind="text: Brand"></span>
            </div>
            
        </div>
    </div>
</div>

MiintoTasks/MiintoTasks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("CSS Task", "Index", "CssTask")</li>
                    <li>@Html.ActionLink(".NET Task", "Index", "NetTask")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/vendor")
    @RenderSection("scripts", required: false)
</body>
</html>